#!/bin/bash

export SECRETS=".secrets.json"

PROJECT=$(realpath $(dirname $(git rev-parse --git-dir)))

# Automate finding tests to execute
cd $PROJECT/tests
FILES=$(find -executable -not -path "\." | grep -v $(basename $0))

# The base status of tests is a pass
cd $PROJECT
STATUS=0

run_test () {
    if [ ${TEST##*.} = "py" ]
    then
        python3 -B $PROJECT/tests/$TEST
    else
        $PROJECT/tests/$TEST
    fi
}

for TEST in $FILES
do
    if [ "$1" = "--silence-pass" ] # silence passing
    then
        run_test $TEST 1>/dev/null
    elif [ "$1" = "--silence-warn" ] # silence pass and warn
    then
        WARN=$(run_test $TEST 2>&1 1>/dev/null)
        if [ $? -gt 0 ]
        then
            echo $WARN
        fi
    else
        run_test $TEST
    fi

    STATUS=$(( $STATUS | $? )) # OR current status with return code
done

exit $STATUS
